"""
Tax Report Service - Generates IRS Form 8949 and other tax reports
"""
import logging
from typing import Dict, List, Any, Optional
from datetime import datetime
import csv
import io

logger = logging.getLogger(__name__)

class TaxReportService:
    """Service for generating tax reports including IRS Form 8949"""
    
    def __init__(self):
        self.form_8949_headers = [
            'Description of property',
            'Date acquired',
            'Date sold or disposed',
            'Proceeds (sales price)',
            'Cost or other basis',
            'Gain or (loss)',
            'Holding period'
        ]
    
    def generate_form_8949_csv(
        self,
        realized_gains: List[Dict[str, Any]],
        symbol: str,
        address: str,
        filter_type: str = 'all'
    ) -> str:
        """
        Generate IRS Form 8949 compatible CSV
        
        Args:
            realized_gains: List of realized gain transactions
            symbol: Cryptocurrency symbol (ETH, BTC, etc.)
            address: Wallet address
            filter_type: 'all', 'short-term', or 'long-term'
        
        Returns:
            CSV content as string
        """
        try:
            output = io.StringIO()
            
            # Filter by holding period if specified
            filtered_gains = realized_gains
            if filter_type == 'short-term':
                filtered_gains = [g for g in realized_gains if g.get('holding_period') == 'short-term']
            elif filter_type == 'long-term':
                filtered_gains = [g for g in realized_gains if g.get('holding_period') == 'long-term']
            
            # Write header information
            output.write('IRS Form 8949 - Sales and Other Dispositions of Capital Assets\n')
            output.write(f'Generated by Crypto Bag Tracker\n')
            output.write(f'Wallet Address: {address}\n')
            output.write(f'Asset: {symbol}\n')
            output.write(f'Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}\n')
            output.write(f'Filter: {filter_type.replace("-", " ").title()}\n')
            output.write('\n')
            
            # Determine which part of Form 8949 this goes in
            if filter_type == 'short-term':
                output.write('Part I - Short-term capital gains and losses (assets held one year or less)\n')
                output.write('Check Box A, B, or C per IRS instructions\n')
            elif filter_type == 'long-term':
                output.write('Part II - Long-term capital gains and losses (assets held more than one year)\n')
                output.write('Check Box D, E, or F per IRS instructions\n')
            else:
                output.write('Combined Short-term and Long-term Report\n')
            
            output.write('\n')
            
            # Write CSV data
            writer = csv.writer(output)
            writer.writerow(self.form_8949_headers)
            
            total_proceeds = 0
            total_cost_basis = 0
            total_gain_loss = 0
            
            for gain in filtered_gains:
                description = f"{gain.get('amount', 0):.8f} {symbol}"
                date_acquired = gain.get('buy_date', 'Various')
                date_sold = gain.get('sell_date', 'Unknown')
                proceeds = gain.get('proceeds', 0)
                cost_basis = gain.get('cost_basis', 0)
                gain_loss = gain.get('gain_loss', 0)
                holding_period = gain.get('holding_period', 'unknown')
                
                writer.writerow([
                    description,
                    date_acquired,
                    date_sold,
                    f'{proceeds:.2f}',
                    f'{cost_basis:.2f}',
                    f'{gain_loss:.2f}',
                    holding_period.title()
                ])
                
                total_proceeds += proceeds
                total_cost_basis += cost_basis
                total_gain_loss += gain_loss
            
            # Write totals
            output.write('\n')
            writer.writerow([
                'TOTALS',
                '',
                '',
                f'{total_proceeds:.2f}',
                f'{total_cost_basis:.2f}',
                f'{total_gain_loss:.2f}',
                ''
            ])
            
            # Add summary
            output.write('\n')
            output.write(f'Total Transactions: {len(filtered_gains)}\n')
            output.write(f'Total Proceeds: ${total_proceeds:.2f}\n')
            output.write(f'Total Cost Basis: ${total_cost_basis:.2f}\n')
            output.write(f'Net Gain/(Loss): ${total_gain_loss:.2f}\n')
            
            # Add disclaimer
            output.write('\n')
            output.write('DISCLAIMER: This report is generated for informational purposes only.\n')
            output.write('Consult a qualified tax professional for advice specific to your situation.\n')
            output.write('Crypto Bag Tracker is not responsible for any errors or omissions.\n')
            
            return output.getvalue()
            
        except Exception as e:
            logger.error(f"Error generating Form 8949: {str(e)}")
            raise Exception(f"Failed to generate Form 8949: {str(e)}")
    
    def generate_tax_summary_csv(
        self,
        tax_data: Dict[str, Any],
        symbol: str,
        address: str
    ) -> str:
        """Generate comprehensive tax summary CSV"""
        try:
            output = io.StringIO()
            
            summary = tax_data.get('summary', {})
            realized = tax_data.get('realized_gains', [])
            unrealized = tax_data.get('unrealized_gains', {})
            
            # Header
            output.write('Crypto Bag Tracker - Tax Summary Report\n')
            output.write(f'Wallet Address: {address}\n')
            output.write(f'Asset: {symbol}\n')
            output.write(f'Method: {tax_data.get("method", "FIFO")}\n')
            output.write(f'Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}\n')
            output.write('\n')
            
            # Summary Section
            output.write('=== SUMMARY ===\n')
            output.write(f'Total Realized Gains/Losses: ${summary.get("total_realized_gain", 0):.2f}\n')
            output.write(f'  - Short-term: ${summary.get("short_term_gains", 0):.2f}\n')
            output.write(f'  - Long-term: ${summary.get("long_term_gains", 0):.2f}\n')
            output.write(f'Total Unrealized Gains: ${summary.get("total_unrealized_gain", 0):.2f}\n')
            output.write(f'Total Transactions: {summary.get("total_transactions", 0)}\n')
            output.write(f'  - Buys: {summary.get("buy_count", 0)}\n')
            output.write(f'  - Sells: {summary.get("sell_count", 0)}\n')
            output.write('\n')
            
            # Holdings Section
            if unrealized:
                output.write('=== CURRENT HOLDINGS ===\n')
                output.write(f'Total Cost Basis: ${unrealized.get("total_cost_basis", 0):.2f}\n')
                output.write(f'Current Market Value: ${unrealized.get("total_current_value", 0):.2f}\n')
                output.write(f'Unrealized Gain/Loss: ${unrealized.get("total_gain", 0):.2f}\n')
                output.write(f'Return: {unrealized.get("total_gain_percentage", 0):.2f}%\n')
            
            output.write('\n')
            output.write('=== DETAILED TRANSACTIONS ===\n')
            
            # Realized gains detail
            writer = csv.writer(output)
            writer.writerow([
                'Type', 'Buy Date', 'Sell Date', 'Amount', 
                'Buy Price', 'Sell Price', 'Cost Basis', 
                'Proceeds', 'Gain/Loss', 'Holding Period'
            ])
            
            for gain in realized:
                writer.writerow([
                    'Disposition',
                    gain.get('buy_date', ''),
                    gain.get('sell_date', ''),
                    f"{gain.get('amount', 0):.8f}",
                    f"{gain.get('buy_price', 0):.2f}",
                    f"{gain.get('sell_price', 0):.2f}",
                    f"{gain.get('cost_basis', 0):.2f}",
                    f"{gain.get('proceeds', 0):.2f}",
                    f"{gain.get('gain_loss', 0):.2f}",
                    gain.get('holding_period', 'unknown')
                ])
            
            return output.getvalue()
            
        except Exception as e:
            logger.error(f"Error generating tax summary: {str(e)}")
            raise Exception(f"Failed to generate tax summary: {str(e)}")
    
    def categorize_transaction(
        self,
        tx: Dict[str, Any],
        category: str
    ) -> Dict[str, Any]:
        """
        Apply category to transaction for tax purposes
        
        Categories affect tax treatment:
        - trade: Taxable event, subject to capital gains
        - income: Ordinary income (mining, staking, airdrops)
        - gift_received: Cost basis = fair market value at time of gift
        - gift_sent: No tax event (but may have gift tax implications)
        - payment: Taxable at fair market value
        - transfer: Not a taxable event
        - lost: May be deductible as a capital loss
        - fee: Adds to cost basis
        """
        tx['category'] = category
        tx['tax_treatment'] = self._get_tax_treatment(category)
        return tx
    
    def _get_tax_treatment(self, category: str) -> Dict[str, Any]:
        """Get tax treatment based on category"""
        treatments = {
            'trade': {
                'taxable': True,
                'type': 'capital_gains',
                'description': 'Subject to capital gains tax'
            },
            'income': {
                'taxable': True,
                'type': 'ordinary_income',
                'description': 'Taxed as ordinary income at receipt'
            },
            'gift_received': {
                'taxable': False,
                'type': 'gift',
                'description': 'Not taxable; cost basis carries over or FMV'
            },
            'gift_sent': {
                'taxable': False,
                'type': 'gift',
                'description': 'No income tax; may have gift tax implications'
            },
            'payment': {
                'taxable': True,
                'type': 'capital_gains',
                'description': 'Taxable at fair market value'
            },
            'transfer': {
                'taxable': False,
                'type': 'non_taxable',
                'description': 'Not a taxable event'
            },
            'lost': {
                'taxable': True,
                'type': 'capital_loss',
                'description': 'May be deductible as capital loss'
            },
            'fee': {
                'taxable': False,
                'type': 'cost_basis',
                'description': 'Added to cost basis'
            },
            'other': {
                'taxable': True,
                'type': 'unknown',
                'description': 'Review and categorize properly'
            }
        }
        return treatments.get(category, treatments['other'])


# Initialize global service
tax_report_service = TaxReportService()
